// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package main

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson73513f99DecodeModel(in *jlexer.Lexer, out *_nodes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "addr":
			out.Addr = string(in.String())
		case "weigh":
			out.Weigh = int32(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson73513f99EncodeModel(out *jwriter.Writer, in _nodes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"addr\":"
		out.RawString(prefix[1:])
		out.String(string(in.Addr))
	}
	{
		const prefix string = ",\"weigh\":"
		out.RawString(prefix)
		out.Int32(int32(in.Weigh))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v _nodes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson73513f99EncodeModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v _nodes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson73513f99EncodeModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *_nodes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson73513f99DecodeModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *_nodes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson73513f99DecodeModel(l, v)
}
func easyjson73513f99DecodeModel1(in *jlexer.Lexer, out *Upstream) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "string":
			out.Desc = string(in.String())
		case "nodes":
			if in.IsNull() {
				in.Skip()
				out.Nodes = nil
			} else {
				in.Delim('[')
				if out.Nodes == nil {
					if !in.IsDelim(']') {
						out.Nodes = make([]*_nodes, 0, 8)
					} else {
						out.Nodes = []*_nodes{}
					}
				} else {
					out.Nodes = (out.Nodes)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *_nodes
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(_nodes)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Nodes = append(out.Nodes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson73513f99EncodeModel1(out *jwriter.Writer, in Upstream) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"string\":"
		out.RawString(prefix[1:])
		out.String(string(in.Desc))
	}
	{
		const prefix string = ",\"nodes\":"
		out.RawString(prefix)
		if in.Nodes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Nodes {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Upstream) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson73513f99EncodeModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Upstream) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson73513f99EncodeModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Upstream) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson73513f99DecodeModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Upstream) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson73513f99DecodeModel1(l, v)
}
